### ISSUE TITLE
Label names for the on screen display.

### ISSUE THREAD

**Issue by RealAmethyst** [manfeed/skin.aeon.tajo#105]
Hi. I use Kodi with a text to speech addon that reads out the UI elements. I have very low vision so I need this to use Kodi. The OSD (the thing that pops up when you click enter with your keyboard when watching something) does not read out by that addon. I'm guessing that's because there's no labels there. Would it be possible to ad that? Thanks!

**Comment by manfeed** [comment]
I have seen other skins and none shows any label in the OSD, only the button images. Anyway, i guess that what you ask for must be something similar to this, isn't it?...

![screenshot00003](https://github.com/manfeed/skin.aeon.tajo/assets/13109584/10d5622f-613e-445a-a52d-923e40d539d2)

**Comment by RealAmethyst** [comment]
Sorry, but I am fully blind, so can't see images. I use a speech software to type this. I know for a fact the confluence skin has a working OSD with the speech addon, as that is what I mainly use, but this skin has features I really like. And that confluense isn't on V21 as far as I know.

**Comment by manfeed** [comment]
Ok, don't worry, now when you bring up the OSD a word will appear beside the button row that describes what the button currently focused does if it's clicked. I hope that will work with your speech addon. Anyway, some time could go by until I release a new version with this feature, so you'll have to be patient...

**Comment by RealAmethyst** [comment]
Thanks a lot! I'll give feedback on it if it works or not when it releases. Hopefully it does. Thanks again!
