### ISSUE TITLE
missing back level in Series

### ISSUE THREAD

**Issue by Sekisback** [manfeed/skin.aeon.tajo#107]
If you want to jump back via remote control from a series session it jumps straight to the main menu.

main menu -> series -> series -> session -> episode

problem occurs if you have more than one series session. 
If i have only on session i can jump back from episode to series.
Using Shelf 3d View

I am using Kodi Omega on Raspberry Pi4, tested also on Nexus, same behaviour.
Used Kodi Matrix till a few days before, didn't had the behaviour on Matrix.

**Comment by manfeed** [comment]
I can replicate the issue. In the next version of the skin it'll be fixed. Thanks!
