### ISSUE TITLE
Unable to select "View Options" menu from "MultiWall"

### ISSUE THREAD

**Issue by rivy** [manfeed/skin.aeon.tajo#16]
No variation of arrow keys (or other random keys) pulls up the "View Options" window after "MultiWall" is selected.
How can it be turned back off?

Looks like it's been a problem for a while ... see <https://www.reddit.com/r/kodi/comments/ehgm33/aeon_tajo_skin_help>.

**Comment by manfeed** [comment]
It’s not a problem... Stay still in a movie for some seconds until a pulsing message appears, from that moment on, if you press Intro, you will see the view options instead of playing the movie. It’s what that message says...

**Comment by rivy** [comment]
That works, thanks!

Excellent work on the skin; thanks for that as well!
