### ISSUE TITLE
Skin font cannot be adjusted

### ISSUE THREAD

**Issue by Bl4ck-H34d** [manfeed/skin.aeon.tajo#3]
The skins font does not allow to show Chinese or Japanese characters and cannot be changed to arial based font.

The skin option in the menu is greyed out.

**Comment by Bl4ck-H34d** [comment]
Hi Manfeed, could you please include a traditional Chinese and Japanese char set / font into the skin?
I am a German living in Taiwan and using chinese Netflix. Those rectangles where the Chinese characters should be are really an eyesore.
Thank you so much!

**Comment by manfeed** [comment]
Solved
