### ISSUE TITLE
Picture slideshow Stops when Music(song) changes

### ISSUE THREAD

**Issue by freak999** [manfeed/skin.aeon.tajo#4]
My picture slideshow stops every time , when the music player starts a new song

**Comment by manfeed** [comment]
It's supposed to be fixed now, with this new version in github, thanks. It's better to tell about bugs in the official thread...
https://forum.kodi.tv/showthread.php?tid=338895
...since there everybody can know about it.

**Comment by freak999** [comment]
Hello Manfred, this version works fine👍😄I‘m very glad. I like this Skin  very much. So now I  have a very nice skin, with all funktionsfähig I need. If l habe a problem next time, I will post in the Kodi forum.
