### ISSUE TITLE
new flags

### ISSUE THREAD

**Issue by Konon-cat** [manfeed/skin.aeon.tajo#42]
I propose 2 new flags - [opus](https://en.wikipedia.org/wiki/Opus_(audio_format)) audio codec and [vp9](https://en.wikipedia.org/wiki/VP9) video codec. If you need to make or redo existing flags, just tell me.
[flag.zip](https://github.com/manfeed/skin.aeon.tajo/files/6527171/flag.zip)

**Comment by manfeed** [comment]
Already added, thanks!

**Comment by Konon-cat** [comment]
I tested it. For some reason, new flags are not displayed.

**Comment by Konon-cat** [comment]
> Already added, thanks!

I tested it. For some reason, new flags are not displayed.

**Comment by manfeed** [comment]
> I tested it. For some reason, new flags are not displayed.

It doesn’t surprise me, for the flags to be displayed kodi must return the corresponding value, and as you can see in…

https://kodi.wiki/view/InfoLabels#ListItem

…there’s no mention to those values in ListItem.VideoCodec and ListItem.AudioCodec yet…
