### ISSUE TITLE
> Already added, thanks!

### ISSUE THREAD

**Issue by Konon-cat** [manfeed/skin.aeon.tajo#43]
> Already added, thanks!

I tested it. For some reason, new flags are not displayed.

_Originally posted by @Konon-cat in https://github.com/manfeed/skin.aeon.tajo/issues/42#issuecomment-846596901_

**Comment by manfeed** [comment]
It doesn’t surprise me, for the flags to be displayed kodi must return the corresponding value, and as you can see in…

https://kodi.wiki/view/InfoLabels#ListItem

…there’s no mention to those values in ListItem.VideoCodec and ListItem.AudioCodec yet…

**Comment by manfeed** [comment]
Out of curiosity I tested two sample files (opus and VP9) and found that both are returned by Kodi 19. VP9 logo is displayed in Aeon Tajo when playing this sample video and pressing the 'I' key...

![111](https://user-images.githubusercontent.com/13109584/120085843-bf03cc00-c0db-11eb-8b3d-39f1bb51a249.jpg)

About the opus sample I realized that Aeon Tajo doesn't use icon flags for audio codecs, but when playing the sample, the word 'opus' is also showed when in Music visualisation screen...

![222](https://user-images.githubusercontent.com/13109584/120085905-76004780-c0dc-11eb-9ff5-f0070088df29.jpg)
