### ISSUE TITLE
Music stop playing

### ISSUE THREAD

**Issue by fernandojconti** [manfeed/skin.aeon.tajo#67]
Hi.

When music is playing and screensaver (Dim) is activated, music stop playing after screensaver wake up moving the mouse or pressing a key.

**Comment by manfeed** [comment]
Just tested and I don't have that issue. Make sure you're using the latest version of the skin (4.6.8.) since in a former version there was an issue with screensavers that was fixed.

**Comment by manfeed** [comment]
Finally I was able to reproduce this, but as I thought, it's in an older version (4.3.0). I don't know why but it seems that for some users 4.3.0 is the latest version available from the official repo... Today I have asked to include in the official repo a new version 4.7.2. Let's hope it reachs all users...

**Comment by fernandojconti** [comment]
> Just tested and I don't have that issue. Make sure you're using the latest version of the skin (4.6.8.) since in a former version there was an issue with screensavers that was fixed.



> Finally I was able to reproduce this, but as I thought, it's in an older version (4.3.0). I don't know why but it seems that for some users 4.3.0 is the latest version available from the official repo... Today I have asked to include in the official repo a new version 4.7.2. Let's hope it reachs all users...

Thanks for your concern. 4.6.5 version was available for me on 19.2. Now with 4.6.8, the issue was fixed.
