### ISSUE TITLE
Latest update of aeonTAJO for Android ARMV8A and ARMV7A stops showing thumbs of album picture in album view and in file view of music library.

### ISSUE THREAD

**Issue by JayDotEll** [manfeed/skin.aeon.tajo#88]
Dear Manfeed,
contratulations and big thanks on your continuessly great work on my favourite skin aeonTAJO.

In addition to my big Android TV I am using five additional Android devices with Kodi and aeonTajo as music player. 
I have successfully updated to Nexus last month and was happy that everything was working fine seamlessly using aeonTAJO.
I recently noticed, that with the latest automatic update of aeonTAJO to Version 5.4.0 (as listed as the latest of recently updated addons) the thumbs in the Album view disappeared as well as the thumbs in the file view of the music library.
To check, if this was related to the aeonTAJO update, I checked on one of the other device. Before the update all Thumbs were showing fine. Once the update was active, the issue was also on this device. I have checked on four other devices, either ARMV8A or ARMV7A. Issue allways starts as soon as aeonTAJO is updating and showing aeonTAJO as the most recent updated addon.
Can you kindly check?

Thanks a lot for your kind help and again for creating and supporting this great skin.
Best regards,
JayDotEll

**Comment by manfeed** [comment]
Ok, I changed list view a lot, and that was a side effect of the changes. The next version will behave as previously.

**Comment by JayDotEll** [comment]
Thanks for the rapid and excellent solution!
