### ISSUE TITLE
Skin Freezes when accessing some youtube channels

### ISSUE THREAD

**Issue by Rferreira2k** [manfeed/skin.aeon.tajo#90]
Skin Freezes kodi when accessing some youtube channels. Other skins (aeon nox, estuary, etc) works fine.

Example of channel where the problem happens: NoCopyrightSounds

Tested with clean kodi 20 instalation + Aeon 5.4.0

![Captura de tela 2023-02-08 091901](https://user-images.githubusercontent.com/92768950/217532108-a0a13761-81ba-4b9c-a712-791a4087544a.jpg)

Kodi log: https://pastebin.pl/view/5de2c03d (dont generate kodi crashlog)

**Comment by manfeed** [comment]
Maybe you have the option to play melodies while in the home menu activated?

**Comment by Rferreira2k** [comment]
> Maybe you have the option to play melodies while in the home menu activated?

No, this options is disabled.

**Comment by Rferreira2k** [comment]
Solved with Kodi 20.1 + Skin 5.9.0

Thanks a lot!
